from __future__ import annotations

import json
from pathlib import Path

from jinja2 import Template

from jannat_reports.network import build_claude_export


TEMPLATE = r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jannat — подробный консолидированный отчёт</title><style>
:root{--navy:#182033;--gold:#b8952a;--bg:#f4f5f7;--ink:#252a3a;--line:#dfe3ea;--green:#25724a;--red:#b63b35;--amber:#b77800;--blue:#315b9c}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px Arial,sans-serif}header{background:var(--navy);color:#fff;border-bottom:4px solid var(--gold);padding:22px max(14px,calc((100% - 1320px)/2))}h1{font:28px Georgia,serif;margin:0 0 7px}.sub{color:#d4d8e2}.wrap{max-width:1320px;margin:auto;padding:16px}.toolbar,.panel,.card{background:#fff;border:1px solid var(--line);border-radius:12px;box-shadow:0 1px 3px #0000000a}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;padding:12px;margin-bottom:13px}.toolbar button,.toolbar select{border:1px solid var(--line);background:#fff;border-radius:8px;padding:9px 13px;font-weight:700}.toolbar button.active{background:var(--navy);color:#fff}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:13px}.card{padding:14px}.card small{color:#687084}.value{font-size:22px;font-weight:800;margin-top:7px}.panel{padding:15px;margin-bottom:13px}h2{font:21px Georgia,serif;margin:2px 0 12px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:950px}th{background:#30394f;color:#fff}th,td{padding:9px;border:1px solid var(--line);text-align:right}th:first-child,td:first-child{text-align:left}.hotel-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.hotel{border:1px solid var(--line);border-radius:11px;overflow:hidden;background:#fff}.hotel-head{background:var(--navy);color:#fff;padding:12px 14px;font-weight:800}.hotel-head span{display:block;color:#d6dae4;font-size:12px;font-weight:400;margin-top:3px}.hotel-body{padding:10px 13px}.row{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid #eceef2;padding:7px 0}.row.total{font-weight:800;border-top:2px solid var(--gold)}.details{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}.note{padding:9px 11px;border-left:4px solid var(--blue);background:#f0f5ff;margin-top:9px;white-space:pre-line}.warn{border-left-color:var(--amber);background:#fff7e8}.bad{color:var(--red)}.good{color:var(--green)}.pill{display:inline-block;padding:3px 8px;border-radius:20px;background:#eef1f6;font-size:11px}.tasks{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.task{border-left:4px solid var(--gold);background:#fafafa;padding:10px}.hidden{display:none}@media(max-width:800px){.cards,.hotel-grid,.tasks{grid-template-columns:1fr 1fr}.details{grid-template-columns:1fr}.value{font-size:19px}}@media(max-width:520px){.cards,.hotel-grid,.tasks{grid-template-columns:1fr}.wrap{padding:10px}h1{font-size:23px}}
</style></head><body><header><h1>Консолидированный отчёт сети</h1><div class="sub" id="headerSub"></div></header><main class="wrap">
<section class="toolbar"><b>Дата:</b><select id="dateSelect"></select><button data-mode="day" class="active">День</button><button data-mode="period">Период</button><button data-mode="month">Месяц</button></section>
<section class="cards" id="summary"></section><section class="panel hidden" id="claudePanel"><h2>🤖 Управленческий анализ Claude</h2><div id="claudeAnalysis"></div></section><section class="panel"><h2 id="financeTitle">Финансовая консолидация</h2><div class="table-wrap"><table><thead><tr><th>Объект</th><th>План дохода</th><th>Факт</th><th>%</th><th>План расходов</th><th>Факт</th><th>План GOP</th><th>Факт GOP</th><th>%</th></tr></thead><tbody id="financeRows"></tbody></table></div></section>
<section class="panel"><h2>Подробные карточки объектов</h2><div class="hotel-grid" id="hotelCards"></div></section><section class="panel" id="salesPanel"><h2>Коммерческий отдел</h2><div id="sales"></div></section><section class="panel" id="tasksPanel"><h2>Мой день — задачи директора</h2><div class="tasks" id="tasks"></div></section><section class="panel"><h2>Контроль данных</h2><div id="warnings"></div></section></main>
<script id="report-data" type="application/json">{{ payload }}</script><script>
const DATA=JSON.parse(document.getElementById('report-data').textContent);let mode='day';const money=v=>Math.round(Number(v||0)).toLocaleString('ru-RU')+' сом',num=v=>Math.round(Number(v||0)).toLocaleString('ru-RU'),pct=v=>Number.isFinite(v)?v.toFixed(1)+'%':'—',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const keys=['rooms_sold','b2c','b2b','online','nf','conf','rest','poolbar','banquet','sbt','med','rent','other_income','income','varexp','fixexp','totexp','gop'];const labels={b2c:'B2C',b2b:'B2B',online:'Online',nf:'Итого номерной фонд',conf:'Конференции / залы',rest:'Ресторан à la carte',poolbar:'Пул-бар',banquet:'Банкет / фуршет',sbt:'СБТ / бассейн',med:'Медицинский центр',rent:'Коммерческая аренда',other_income:'Прочие доходы'};
const ds=document.getElementById('dateSelect');DATA.days.forEach((d,i)=>{const o=document.createElement('option');o.value=i;o.textContent=d.report_date.split('-').reverse().join('.');ds.appendChild(o)});ds.value=DATA.days.length-1;const selectedDays=()=>{const i=Number(ds.value);return mode==='day'?[DATA.days[i]]:DATA.days.slice(0,i+1)},bySlug=(d,s)=>d.objects.find(o=>o.slug===s);
function aggregate(slug){const days=selectedDays(),latest=bySlug(days.at(-1),slug),a={...latest};keys.forEach(k=>a[k]=days.reduce((s,d)=>s+Number(bySlug(d,slug)?.[k]||0),0));a.occupancy=a.room_fund?100*a.rooms_sold/(a.room_fund*days.length):0;a.adr=a.rooms_sold?a.nf/a.rooms_sold:0;a.revpar=a.room_fund?a.nf/(a.room_fund*days.length):0;a.trevpar=a.room_fund?a.income/(a.room_fund*days.length):0;return a}function plan(o,k){if(mode==='month')return Number(o.plans?.[k]?.month||0);if(mode==='day')return Number(o.plans?.[k]?.day||0);return selectedDays().reduce((s,d)=>s+Number(bySlug(d,o.slug)?.plans?.[k]?.day||0),0)}const ratio=(a,b)=>b?100*a/b:0,badge=v=>v>=100?'good':v<80?'bad':'';
function render(){const current=DATA.days[Number(ds.value)],objs=current.objects.map(o=>aggregate(o.slug)),date=current.report_date.split('-').reverse().join('.'),lab=mode==='day'?'день':mode==='period'?'период с начала месяца':'месяц: факт на дату / план',total=k=>objs.reduce((s,o)=>s+Number(o[k]||0),0),pi=objs.reduce((s,o)=>s+plan(o,'income'),0),pg=objs.reduce((s,o)=>s+plan(o,'ebitda'),0);document.getElementById('headerSub').textContent=`Дата данных: ${date} · режим: ${lab} · объектов: ${objs.length}`;
document.getElementById('summary').innerHTML=`<div class="card"><small>Доход сети</small><div class="value">${money(total('income'))}</div><span class="pill ${badge(ratio(total('income'),pi))}">${pct(ratio(total('income'),pi))} плана</span></div><div class="card"><small>Операционные расходы</small><div class="value">${money(total('totexp'))}</div></div><div class="card"><small>GOP / EBITDA</small><div class="value ${total('gop')>=0?'good':'bad'}">${money(total('gop'))}</div><span class="pill ${badge(ratio(total('gop'),pg))}">${pct(ratio(total('gop'),pg))} плана</span></div><div class="card"><small>Продано номеров</small><div class="value">${num(total('rooms_sold'))}</div></div>`;
document.getElementById('financeTitle').textContent='Финансовая консолидация — '+lab;document.getElementById('financeRows').innerHTML=objs.map(o=>{const a=plan(o,'income'),e=plan(o,'operating_expenses'),g=plan(o,'ebitda');return `<tr><td><b>${o.name||o.slug}</b><br><small>${o.gm||''}</small></td><td>${money(a)}</td><td>${money(o.income)}</td><td class="${badge(ratio(o.income,a))}">${pct(ratio(o.income,a))}</td><td>${money(e)}</td><td>${money(o.totexp)}</td><td>${money(g)}</td><td class="${o.gop>=0?'good':'bad'}">${money(o.gop)}</td><td>${pct(ratio(o.gop,g))}</td></tr>`}).join('');
document.getElementById('hotelCards').innerHTML=objs.map(o=>{const detail=Object.entries(labels).map(([k,l])=>`<div class="row"><span>${l}</span><b>${money(o[k])}</b></div>`).join(''),n=o.gm_notes||{},w=(o._warning||[]).map(x=>`<div class="note warn">⚠️ ${x}</div>`).join('');return `<article class="hotel"><div class="hotel-head">${o.name||o.slug}<span>${o.gm||'—'} · ${o.room_fund||0} номеров</span></div><div class="hotel-body"><div class="details"><div><div class="row"><span>Продано / загрузка</span><b>${num(o.rooms_sold)} / ${pct(o.occupancy)}</b></div><div class="row"><span>ADR</span><b>${money(o.adr)}</b></div><div class="row"><span>RevPAR / TrevPAR</span><b>${money(o.revpar)} / ${money(o.trevpar)}</b></div>${detail}</div><div><div class="row"><span>Переменные расходы</span><b>${money(o.varexp)}</b></div><div class="row"><span>Постоянные расходы</span><b>${money(o.fixexp)}</b></div><div class="row total"><span>Общие расходы</span><b>${money(o.totexp)}</b></div><div class="row total"><span>Доход</span><b>${money(o.income)}</b></div><div class="row total"><span>GOP / EBITDA</span><b class="${o.gop>=0?'good':'bad'}">${money(o.gop)}</b></div><div class="note"><b>Проблема:</b> ${n.problem||'—'}<br><b>Предпринято:</b> ${n.action||'—'}<br><b>Эскалация:</b> ${n.escalation||'—'}<br><b>Задачи:</b> ${(n.top3||[]).join('; ')||'—'}<br><b>Идея:</b> ${n.idea||'—'}</div>${w}</div></div></div></article>`}).join('');
const s=DATA.sales_dept;if(s)document.getElementById('sales').innerHTML=`<p><b>Дата:</b> ${s.report_date||'—'} · <b>Руководитель:</b> ${s.head||'—'} · <b>Сотрудники:</b> ${s.managers_present||'—'}</p><div class="cards"><div class="card">Звонки<div class="value">${num(s.kpi.calls_fact)} / ${num(s.kpi.calls_plan)}</div></div><div class="card">Встречи<div class="value">${num(s.kpi.meetings_fact)} / ${num(s.kpi.meetings_plan)}</div></div><div class="card">Выручка дня<div class="value">${money(s.kpi.revenue_day)}</div></div><div class="card">Выручка месяца<div class="value">${money(s.kpi.revenue_month_fact)}</div></div></div>`;else document.getElementById('salesPanel').classList.add('hidden');if(DATA.director_tasks?.length)document.getElementById('tasks').innerHTML=DATA.director_tasks.map(t=>`<div class="task"><b>${t.icon||'📄'} ${t.title}</b><div>${t.desc||''}</div></div>`).join('');else document.getElementById('tasksPanel').classList.add('hidden');const ws=objs.flatMap(o=>(o._warning||[]).map(w=>`${o.name}: ${w}`));document.getElementById('warnings').innerHTML=ws.length?ws.map(w=>`<div class="note warn">⚠️ ${w}</div>`).join(''):'<div class="note">✅ Критические расхождения не обнаружены.</div>'}
const a=DATA.claude_analysis;if(a){document.getElementById('claudePanel').classList.remove('hidden');const list=(title,items,cls='')=>{if(!items?.length)return '';const rows=items.map(x=>{const text=typeof x==='string'?x:`${x.hotel?x.hotel+': ':''}${x.issue||x.action||x.insight||''}`;return `<div class="note ${cls}">${esc(text)}</div>`}).join('');return `<h3>${title}</h3>${rows}`};document.getElementById('claudeAnalysis').innerHTML=`<p>${esc(a.executive_summary||'')}</p>${list('Сильные результаты',a.highlights)}${list('Риски',a.risks,'warn')}${list('Рекомендуемые действия',a.actions)}`}
ds.onchange=render;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));render()});render();
</script></body></html>'''


def render_network_report(data: dict, output: str | Path, export_data: dict | None = None) -> None:
    payload = json.dumps(export_data or build_claude_export(data), ensure_ascii=False).replace("</", "<\\/")
    Path(output).write_text(Template(TEMPLATE).render(payload=payload), encoding="utf-8")
