from __future__ import annotations

from pathlib import Path

from jinja2 import Template


TEMPLATE = r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jannat — консолидированный отчёт</title><style>
:root{--gold:#b8952a;--navy:#172033;--ink:#24283a;--bg:#f4f5f7;--line:#dde1e8;--green:#26734a;--red:#b63832;--amber:#b87600}*{box-sizing:border-box}body{margin:0;background:var(--bg);font:14px Arial;color:var(--ink)}header{background:var(--navy);color:#fff;border-bottom:4px solid var(--gold);padding:24px max(16px,calc((100% - 1250px)/2))}h1{font:28px Georgia;margin:0 0 7px}.wrap{max-width:1250px;margin:auto;padding:18px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.card,.panel{background:#fff;border:1px solid var(--line);border-radius:12px;padding:15px;margin-bottom:14px}.value{font-size:22px;font-weight:800;margin-top:7px}h2{font:21px Georgia;margin:2px 0 13px}.tbl{overflow:auto}table{border-collapse:collapse;width:100%;min-width:900px}th{background:#30394f;color:#fff}th,td{padding:9px;border:1px solid var(--line);text-align:right}th:first-child,td:first-child{text-align:left}.ok{color:var(--green)}.bad{color:var(--red)}.muted{color:#687084}.op{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.op article{border-left:4px solid var(--gold);padding:4px 12px;background:#fafafa}.notes p{white-space:pre-line}@media(max-width:760px){.cards,.op{grid-template-columns:1fr 1fr}.value{font-size:18px}}@media(max-width:520px){.cards,.op{grid-template-columns:1fr}}
</style></head><body><header><h1>Консолидированный отчёт сети</h1><div>Дата данных: {{ d.report_sheet }}.2026 · объектов: {{ d.hotels|length }} · проверка: {{ 'без расхождений' if d.verified else 'есть замечания' }}</div></header><main class="wrap">
<section class="cards"><div class="card"><small>Доход по кассе, накопительно</small><div class="value">{{ money(t.income.fact_accum) }}</div></div><div class="card"><small>Доход без налога</small><div class="value">{{ money(t.income_net.fact_accum) }}</div></div><div class="card"><small>GOP / EBITDA</small><div class="value {{ 'ok' if t.ebitda.fact_accum >= 0 else 'bad' }}">{{ money(t.ebitda.fact_accum) }}</div></div><div class="card"><small>Выполнение плана доходов</small><div class="value">{{ pct(t.income_completion) }}</div></div></section>
<section class="panel"><h2>Финансовая консолидация</h2><div class="tbl"><table><thead><tr><th>Объект</th><th>План доходов</th><th>Доход день</th><th>Доход накопл.</th><th>Без налога</th><th>Расходы</th><th>GOP / EBITDA</th><th>% плана</th></tr></thead><tbody>{% for h in d.hotels %}<tr><td><b>{{ h.meta.hotel }}</b></td><td>{{ money(h.metrics.income.plan_month) }}</td><td>{{ money(h.metrics.income.fact_day) }}</td><td>{{ money(h.metrics.income.fact_accum) }}</td><td>{{ money(h.metrics.income_net.fact_accum) }}</td><td>{{ money(h.metrics.operating_expenses.fact_accum) }}</td><td class="{{ 'ok' if h.metrics.ebitda.fact_accum >= 0 else 'bad' }}">{{ money(h.metrics.ebitda.fact_accum) }}</td><td>{{ pct(h.metrics.income.accum_pct) }}</td></tr>{% endfor %}<tr><td><b>ИТОГО СЕТЬ</b></td><td>{{ money(t.income.plan_month) }}</td><td>{{ money(t.income.fact_day) }}</td><td>{{ money(t.income.fact_accum) }}</td><td>{{ money(t.income_net.fact_accum) }}</td><td>{{ money(t.operating_expenses.fact_accum) }}</td><td>{{ money(t.ebitda.fact_accum) }}</td><td>{{ pct(t.income_completion) }}</td></tr></tbody></table></div></section>
<section class="panel"><h2>Номерной фонд по каналам</h2><div class="tbl"><table><thead><tr><th>Объект</th><th>Продано номеров</th><th>B2C</th><th>B2B</th><th>Online</th><th>Итого НФ</th></tr></thead><tbody>{% for h in d.hotels %}<tr><td>{{ h.meta.hotel }}</td><td>{{ num(h.metrics.rooms_sold.fact_accum) }}</td><td>{{ money(h.metrics.b2c.fact_accum) }}</td><td>{{ money(h.metrics.b2b.fact_accum) }}</td><td>{{ money(h.metrics.online.fact_accum) }}</td><td>{{ money(h.metrics.rooms_revenue.fact_accum) }}</td></tr>{% endfor %}</tbody></table></div></section>
<section class="panel"><h2>Оперативные вопросы GM</h2><div class="op">{% for h in d.hotels %}<article><b>{{ h.meta.hotel }}</b><p><b>Проблема:</b> {{ clean(h.operational.incident) }}</p><p><b>Предпринято:</b> {{ clean(h.operational.action) }}</p><p><b>Требует решения:</b> {{ clean(h.operational.escalation) }}</p><p><b>Задачи:</b> {{ clean(h.operational.tomorrow) }}</p></article>{% endfor %}</div></section>
{% if d.commercial %}<section class="panel"><h2>Коммерческий отдел</h2><p><b>Дата файла:</b> {{ d.commercial.meta.date }} · <b>руководитель:</b> {{ d.commercial.meta.leader }}</p><div class="tbl"><table><thead><tr><th>Менеджер</th><th>Звонки</th><th>Встречи</th><th>Компании</th><th>Контракты</th><th>Выручка</th></tr></thead><tbody>{% for x in d.commercial.managers %}<tr><td>{{ x.name }}</td><td>{{ x.calls }}</td><td>{{ x.meetings }}</td><td>{{ x.companies }}</td><td>{{ x.contracts }}</td><td>{{ money(x.revenue) }}</td></tr>{% endfor %}</tbody></table></div><p><b>Результат:</b> {{ d.commercial.texts.result or '—' }}</p><p><b>Проблема:</b> {{ d.commercial.texts.problem or '—' }}</p><p><b>Задачи:</b> {{ d.commercial.texts.tomorrow or '—' }}</p></section>{% endif %}
{% if d.director_notes %}<section class="panel notes"><h2>Отчёт директора по отелям</h2>{% for title,text in d.director_notes.items() %}<p><b>{{ title }}:</b> {{ text }}</p>{% endfor %}</section>{% endif %}
</main></body></html>'''


def render_network_report(data: dict, output: str | Path) -> None:
    num = lambda value: f"{round(float(value or 0)):,}".replace(",", " ")
    money = lambda value: num(value) + " сом"
    pct = lambda value: f"{float(value or 0) * 100:.1f}%"
    clean = lambda value: value if value and not str(value).startswith("[") else "—"
    html = Template(TEMPLATE).render(d=data, t=data["totals"], num=num, money=money, pct=pct, clean=clean)
    Path(output).write_text(html, encoding="utf-8")
